name: Update Awards
on: 
  push:
  schedule:
    - cron: '15 6 * * *' # everyday

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install deps 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Update Awards 
        run: |
          python nsf_awards.py 

      - name: Upload Awards
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "yzz0225@auburn.edu"
          git config --local user.name "Yimin Zhong"
          git add -A 
          git commit -m "Update Awards" || echo "No changes" 
          git push 

